#!/bin/bash
#SBATCH --chdir=
#SBATCH --job-name=pp
#SBATCH --output=postp.out
#SBATCH --error=postp.err
#SBATCH --time=24:00:00
#SBATCH --qos=class_a
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=24
#SBATCH --nodes=1

module purge
module load intel/2020.1
module load impi/2018.4
module load mkl/2020.1
module load boost/1.75.0
module load plumed/2.8.0
module load gromacs/2021.4-plumed.2.8.0

#export FN=$(cd ..; basename -- "$PWD")
export FN=$(basename -- "$PWD")
export GMX=gmx_mpi

tpr=min.tpr
traj=md
ndx=i.ndx

tmax=200000

# Formatting, centering and PBC correction
echo Protein_LIG         | $GMX trjconv -s $tpr -f ${traj}.xtc       -o ${traj}_whole.xtc -pbc whole -n i.ndx
echo Protein Protein_LIG | $GMX trjconv -s $tpr -f ${traj}_whole.xtc -o ${traj}_clust.xtc -pbc cluster -n i.ndx
echo Protein Protein_LIG | $GMX trjconv -s $tpr -f ${traj}_clust.xtc -o ${traj}_final.xtc -pbc mol -ur compact -center -n i.ndx
# Create a short trajectory for viewing
echo Protein_LIG         | $GMX trjconv -s $tpr -f ${traj}_final.xtc -o ${FN}_short.xtc -dt 100 -n i.ndx
# Extract the lastframe as a pdb
echo Protein_LIG         | $GMX trjconv -s $tpr -f ${traj}_final.xtc -o ${FN}_lastframe.pdb -b $tmax -e $tmax -n i.ndx
# RMSD for Ligand and Backbone
echo Backbone Backbone   | $GMX rms     -s $tpr -f ${traj}_final.xtc -o backbone_rmsd.xvg -fit rot+trans -n i.ndx
echo Backbone MOL        | $GMX rms     -s $tpr -f ${traj}_final.xtc -o ligand_rmsd.xvg   -fit rot+trans -n i.ndx
